// ==========================================
// DOM ELEMENT ACCESS (lazy)
// ==========================================

function byId<T extends HTMLElement>(id: string): T {
    const el = document.getElementById(id);
    if (!el) {
        throw new Error(`[UI] Missing required element: #${id}`);
    }
    return el as T;
}

export const ui = {
    get step1() { return byId<HTMLElement>('step-1'); },
    get step2() { return byId<HTMLElement>('step-2'); },
    get stepStyle() { return byId<HTMLElement>('step-style'); },
    get backBtn() { return byId<HTMLButtonElement>('back-btn'); },
    get mainCta() { return byId<HTMLButtonElement>('main-cta'); },
    get editModeBtn() { return byId<HTMLButtonElement>('edit-mode-btn'); },

    get chartTypeWrapper() { return byId<HTMLElement>('chart-type-wrapper'); },
    get chartTypeIcon() { return byId<HTMLElement>('chart-type-icon'); },
    get chartTypeDisplay() { return byId<HTMLElement>('chart-type-display'); },
    get templateModeBanner() { return byId<HTMLElement>('template-mode-banner'); },
    get tabStyleBtn() { return byId<HTMLButtonElement>('tab-style'); },

    get settingColInput() { return byId<HTMLInputElement>('setting-col-input'); },
    get settingCellInput() { return byId<HTMLInputElement>('setting-cell-input'); },
    get settingMarkSelect() { return byId<HTMLSelectElement>('setting-mark-select'); },
    get graphSettingPanel() { return byId<HTMLElement>('graph-setting-panel'); },
    get graphSettingTooltip() { return byId<HTMLElement>('graph-setting-tooltip'); },
    get graphSettingTooltipImage() { return byId<HTMLImageElement>('graph-setting-tooltip-image'); },
    get graphSettingTooltipTitle() { return byId<HTMLElement>('graph-setting-tooltip-title'); },
    get graphSettingTooltipBody() { return byId<HTMLElement>('graph-setting-tooltip-body'); },

    get containerMarkWrapper() { return byId<HTMLElement>('container-mark-wrapper'); },
    get containerMarkNormal() { return byId<HTMLElement>('container-mark-normal'); },

    get labelColInput() { return byId<HTMLElement>('label-col-input'); },
    get labelMarkPosition() { return byId<HTMLElement>('label-mark-position'); },

    get settingYMin() { return byId<HTMLInputElement>('setting-y-min'); },
    get settingYMax() { return byId<HTMLInputElement>('setting-y-max'); },
    get settingYLabelFormat() { return byId<HTMLSelectElement>('setting-y-label-format'); },
    get settingMarkRatioInput() { return byId<HTMLSelectElement>('setting-mark-ratio-input'); },

    get settingStrokeInput() { return byId<HTMLInputElement>('setting-stroke-input'); },
    get containerMarkRatio() { return byId<HTMLElement>('container-mark-ratio'); },
    get containerStrokeWidth() { return byId<HTMLElement>('container-stroke-width'); },
    get spacerStroke() { return byId<HTMLElement>('spacer-stroke'); },

    get csvInput() { return byId<HTMLInputElement>('csv-upload'); },
    get csvStatusText() { return byId<HTMLElement>('csv-status-text'); },
    get csvDeleteBtn() { return byId<HTMLButtonElement>('csv-delete-btn'); },

    get gridScrollArea() { return byId<HTMLElement>('grid-scroll-area'); },
    get gridContainer() { return byId<HTMLElement>('data-grid'); },
    get rowHeaderContainer() { return byId<HTMLElement>('row-header-container'); },
    get stylePreviewContainer() { return byId<HTMLElement>('style-preview-container'); },

    get addColFixedBtn() { return byId<HTMLButtonElement>('add-col-fixed-btn'); },
    get addRowFixedBtn() { return byId<HTMLButtonElement>('add-row-fixed-btn'); },
    get resetBtn() { return byId<HTMLButtonElement>('reset-btn'); },

    get modeToggleContainer() { return byId<HTMLElement>('mode-toggle-container'); },
    get modeRawBtn() { return byId<HTMLButtonElement>('mode-raw'); },
    get modePercentBtn() { return byId<HTMLButtonElement>('mode-percent'); },
    get assistLineControl() { return byId<HTMLElement>('assist-line-control'); },
    get assistLineLabelBtn() { return byId<HTMLButtonElement>('assist-line-label-btn'); },
    get assistLineToggleBtn() { return byId<HTMLButtonElement>('assist-line-toggle'); },
    get assistLinePopover() { return byId<HTMLElement>('assist-line-popover'); },
    get assistLineMinCheck() { return byId<HTMLInputElement>('assist-line-min-check'); },
    get assistLineMaxCheck() { return byId<HTMLInputElement>('assist-line-max-check'); },
    get assistLineAvgCheck() { return byId<HTMLInputElement>('assist-line-avg-check'); },
    get assistLineCtrCheck() { return byId<HTMLInputElement>('assist-line-ctr-check'); },
    get styleAssistLineControl() { return byId<HTMLElement>('style-assist-line-control'); },
    get styleAssistLineLabelBtn() { return byId<HTMLButtonElement>('style-assist-line-label-btn'); },
    get styleAssistLineToggleBtn() { return byId<HTMLButtonElement>('style-assist-line-toggle'); },
    get styleAssistLinePopover() { return byId<HTMLElement>('style-assist-line-popover'); },
    get styleAssistLineMinCheck() { return byId<HTMLInputElement>('style-assist-line-min-check'); },
    get styleAssistLineMaxCheck() { return byId<HTMLInputElement>('style-assist-line-max-check'); },
    get styleAssistLineAvgCheck() { return byId<HTMLInputElement>('style-assist-line-avg-check'); },
    get styleAssistLineCtrCheck() { return byId<HTMLInputElement>('style-assist-line-ctr-check'); },

    get tooltipNormal() { return byId<HTMLElement>('tooltip-normal'); },
    get tooltipWarning() { return byId<HTMLElement>('tooltip-warning'); },
    get mainTooltip() { return byId<HTMLElement>('main-tooltip'); },
    get tooltipStackedHint() { return byId<HTMLElement>('tooltip-stacked-hint'); },

    get csvExportBtn() { return byId<HTMLButtonElement>('csv-export-btn'); },
    get toast() { return byId<HTMLElement>('restore-toast'); },
    get toastYesBtn() { return byId<HTMLButtonElement>('toast-yes-btn'); },
    get toastCloseBtn() { return byId<HTMLButtonElement>('toast-close-btn'); },
    get errorToast() { return byId<HTMLElement>('error-toast'); },

    get rowColorPopover() { return byId<HTMLElement>('row-color-popover'); },
    get rowColorModeTabHex() { return byId<HTMLButtonElement>('row-color-mode-tab-hex'); },
    get rowColorModeTabStyle() { return byId<HTMLButtonElement>('row-color-mode-tab-style'); },
    get rowColorPreview() { return byId<HTMLElement>('row-color-preview'); },
    get rowColorWheel() { return byId<HTMLElement>('row-color-wheel'); },
    get rowColorHexInputBox() { return byId<HTMLElement>('row-color-hex-input-box'); },
    get rowColorHexInput() { return byId<HTMLInputElement>('row-color-hex-input'); },
    get rowColorStyleInputBox() { return byId<HTMLElement>('row-color-style-input-box'); },
    get rowColorStyleChip() { return byId<HTMLElement>('row-color-style-chip'); },
    get rowColorStyleMainSwatch() { return byId<HTMLElement>('row-color-style-main-swatch'); },
    get rowColorStyleChipText() { return byId<HTMLElement>('row-color-style-chip-text'); },
    get rowColorStyleChipEmpty() { return byId<HTMLElement>('row-color-style-chip-empty'); },
    get rowColorStyleChipClose() { return byId<HTMLButtonElement>('row-color-style-chip-close'); },
    get rowColorStyleCaretBtn() { return byId<HTMLButtonElement>('row-color-style-caret-btn'); },
    get rowColorStyleMenu() { return byId<HTMLElement>('row-color-style-menu'); },
    get rowColorStyleMenuList() { return byId<HTMLElement>('row-color-style-menu-list'); },
    get rowColorStyleEditBox() { return byId<HTMLElement>('row-color-style-edit-box'); },
    get rowColorStyleEditHexInput() { return byId<HTMLInputElement>('row-color-style-edit-hex-input'); },
    get rowColorAddBtn() { return byId<HTMLButtonElement>('row-color-add-btn'); },
    get rowColorEditBtn() { return byId<HTMLButtonElement>('row-color-edit-btn'); },
    get rowColorResetBtn() { return byId<HTMLButtonElement>('row-color-reset-btn'); },
    get rowColorSaveBtn() { return byId<HTMLButtonElement>('row-color-save-btn'); },
    get styleColorPopover() { return byId<HTMLElement>('style-item-popover'); },
    get styleColorPopoverTitle() { return byId<HTMLElement>('style-item-popover-title'); },
    get styleColorPreview() { return byId<HTMLElement>('style-item-popover-preview'); },
    get styleColorWheel() { return byId<HTMLElement>('style-item-color-wheel'); },
    get styleColorHexInput() { return byId<HTMLInputElement>('style-item-primary-color-input'); },
    get styleColorSaveBtn() { return byId<HTMLButtonElement>('style-item-save-btn'); },
    get styleItemPopover() { return byId<HTMLElement>('style-item-popover'); },
    get styleItemPopoverTitle() { return byId<HTMLElement>('style-item-popover-title'); },
    get styleItemPopoverPreview() { return byId<HTMLElement>('style-item-popover-preview'); },
    get styleItemNavRow() { return byId<HTMLElement>('style-item-nav-row'); },
    get styleItemSegmentGroup() { return byId<HTMLElement>('style-item-segment-group'); },
    get styleItemSegmentMarkBtn() { return byId<HTMLButtonElement>('style-item-segment-mark'); },
    get styleItemSegmentColumnBtn() { return byId<HTMLButtonElement>('style-item-segment-column'); },
    get styleItemStepper() { return byId<HTMLElement>('style-item-stepper'); },
    get styleItemNavPrevBtn() { return byId<HTMLButtonElement>('style-item-nav-prev'); },
    get styleItemNavNextBtn() { return byId<HTMLButtonElement>('style-item-nav-next'); },
    get styleItemNavLabel() { return byId<HTMLElement>('style-item-nav-label'); },
    get styleItemCloseBtn() { return byId<HTMLButtonElement>('style-item-close-btn'); },
    get styleItemModeTabHex() { return byId<HTMLButtonElement>('style-item-mode-tab-hex'); },
    get styleItemModeTabStyle() { return byId<HTMLButtonElement>('style-item-mode-tab-style'); },
    get styleItemColorWheel() { return byId<HTMLElement>('style-item-color-wheel'); },
    get styleItemStyleRow() { return byId<HTMLElement>('style-item-style-row'); },
    get styleItemStyleSelect() { return byId<HTMLSelectElement>('style-item-style-select'); },
    get styleItemPrimaryColorRow() { return byId<HTMLElement>('style-item-primary-color-row'); },
    get styleItemPrimaryColorLabel() { return byId<HTMLElement>('style-item-primary-color-label'); },
    get styleItemPrimaryColorInput() { return byId<HTMLInputElement>('style-item-primary-color-input'); },
    get styleItemPrimaryColorPreview() { return byId<HTMLElement>('style-item-primary-color-preview'); },
    get styleItemSwatchRow() { return byId<HTMLElement>('style-item-swatch-row'); },
    get styleItemSwatchBlack() { return byId<HTMLButtonElement>('style-item-swatch-black'); },
    get styleItemSwatchGray() { return byId<HTMLButtonElement>('style-item-swatch-gray'); },
    get styleItemSwatchWhite() { return byId<HTMLButtonElement>('style-item-swatch-white'); },
    get styleItemSecondaryColorRow() { return byId<HTMLElement>('style-item-secondary-color-row'); },
    get styleItemSecondaryColorLabel() { return byId<HTMLElement>('style-item-secondary-color-label'); },
    get styleItemSecondaryColorInput() { return byId<HTMLInputElement>('style-item-secondary-color-input'); },
    get styleItemSecondaryColorPreview() { return byId<HTMLElement>('style-item-secondary-color-preview'); },
    get styleItemLinkRow() { return byId<HTMLElement>('style-item-link-row'); },
    get styleItemLinkToggle() { return byId<HTMLInputElement>('style-item-link-toggle'); },
    get styleItemLinkHint() { return byId<HTMLElement>('style-item-link-hint'); },
    get styleItemStrokeRow() { return byId<HTMLElement>('style-item-stroke-row'); },
    get styleItemStrokeStyleInput() { return byId<HTMLSelectElement>('style-item-stroke-style-input'); },
    get styleItemThicknessRow() { return byId<HTMLElement>('style-item-thickness-row'); },
    get styleItemThicknessInput() { return byId<HTMLInputElement>('style-item-thickness-input'); },
    get styleItemOpacityRow() { return byId<HTMLElement>('style-item-opacity-row'); },
    get styleItemOpacityInput() { return byId<HTMLInputElement>('style-item-opacity-input'); },
    get styleItemEnableRow() { return byId<HTMLElement>('style-item-enable-row'); },
    get styleItemEnableInput() { return byId<HTMLInputElement>('style-item-enable-input'); },
    get styleItemVisibleRow() { return byId<HTMLElement>('style-item-visible-row'); },
    get styleItemVisibleInput() { return byId<HTMLInputElement>('style-item-visible-input'); },
    get styleItemSidesRow() { return byId<HTMLElement>('style-item-sides-row'); },
    get styleItemSideTop() { return byId<HTMLInputElement>('style-item-side-top'); },
    get styleItemSideRight() { return byId<HTMLInputElement>('style-item-side-right'); },
    get styleItemSideBottom() { return byId<HTMLInputElement>('style-item-side-bottom'); },
    get styleItemSideLeft() { return byId<HTMLInputElement>('style-item-side-left'); },
    get styleItemCancelBtn() { return byId<HTMLButtonElement>('style-item-cancel-btn'); },
    get styleItemSaveBtn() { return byId<HTMLButtonElement>('style-item-save-btn'); },

    get styleCellTopColorInput() { return byId<HTMLInputElement>('style-cell-top-color'); },
    get styleCellTopThicknessInput() { return byId<HTMLInputElement>('style-cell-top-thickness'); },
    get styleCellTopVisibleInput() { return byId<HTMLInputElement>('style-cell-top-visible'); },
    get styleCellTopStrokeStyleInput() { return byId<HTMLSelectElement>('style-cell-top-stroke-style'); },
    get styleTabRightColorInput() { return byId<HTMLInputElement>('style-tab-right-color'); },
    get styleTabRightThicknessInput() { return byId<HTMLInputElement>('style-tab-right-thickness'); },
    get styleTabRightVisibleInput() { return byId<HTMLInputElement>('style-tab-right-visible'); },
    get styleTabRightStrokeStyleInput() { return byId<HTMLSelectElement>('style-tab-right-stroke-style'); },
    get styleGridColorInput() { return byId<HTMLInputElement>('style-grid-color'); },
    get styleGridThicknessInput() { return byId<HTMLInputElement>('style-grid-thickness'); },
    get styleGridVisibleInput() { return byId<HTMLInputElement>('style-grid-visible'); },
    get styleGridStrokeStyleInput() { return byId<HTMLSelectElement>('style-grid-stroke-style'); },
    get styleGridSideTopInput() { return byId<HTMLInputElement>('style-grid-side-top'); },
    get styleGridSideRightInput() { return byId<HTMLInputElement>('style-grid-side-right'); },
    get styleGridSideBottomInput() { return byId<HTMLInputElement>('style-grid-side-bottom'); },
    get styleGridSideLeftInput() { return byId<HTMLInputElement>('style-grid-side-left'); },
    get styleAssistLineColorInput() { return byId<HTMLInputElement>('style-assist-line-color'); },
    get styleAssistLineThicknessInput() { return byId<HTMLInputElement>('style-assist-line-thickness'); },
    get styleAssistLineStrokeStyleInput() { return byId<HTMLSelectElement>('style-assist-line-stroke-style'); },
    get styleLineBackgroundSection() { return byId<HTMLElement>('style-line-background-section'); },
    get styleLineBackgroundColorInput() { return byId<HTMLInputElement>('style-line-background-color'); },
    get styleLineBackgroundVisibleInput() { return byId<HTMLInputElement>('style-line-background-visible'); },
    get styleMarkLineBackgroundVisibleInput() { return byId<HTMLInputElement>('style-mark-line-background-visible'); },
    get styleMarkFillColorInput() { return byId<HTMLInputElement>('style-mark-fill-color'); },
    get styleMarkStrokeColorInput() { return byId<HTMLInputElement>('style-mark-stroke-color'); },
    get styleMarkLineBackgroundColorInput() { return byId<HTMLInputElement>('style-mark-line-background-color'); },
    get styleMarkLineBackgroundOpacityInput() { return byId<HTMLInputElement>('style-mark-line-background-opacity'); },
    get styleMarkThicknessInput() { return byId<HTMLInputElement>('style-mark-thickness'); },
    get styleMarkStrokeStyleInput() { return byId<HTMLSelectElement>('style-mark-stroke-style'); },
    get styleMarkIndexInput() { return byId<HTMLSelectElement>('style-mark-index'); },
    get styleMarkStrokeToggleRow() { return byId<HTMLElement>('style-mark-stroke-toggle-row'); },
    get styleMarkStrokeToggle() { return byId<HTMLInputElement>('style-mark-stroke-toggle'); },
    get styleMarkStrokeCard() { return byId<HTMLElement>('style-mark-stroke-card'); },
    get styleMarkStrokeSidesTopInput() { return byId<HTMLInputElement>('style-mark-stroke-sides-top'); },
    get styleMarkStrokeSidesLeftInput() { return byId<HTMLInputElement>('style-mark-stroke-sides-left'); },
    get styleMarkStrokeSidesRightInput() { return byId<HTMLInputElement>('style-mark-stroke-sides-right'); },
    get styleMarkFillCard() { return byId<HTMLElement>('style-mark-fill-card'); },
    get styleMarkLineBackgroundCard() { return byId<HTMLElement>('style-mark-line-background-card'); },
    get styleCellFillColorInput() { return byId<HTMLInputElement>('style-cell-fill-color'); },
    get styleCellFillColorPreview() { return byId<HTMLElement>('style-cell-fill-color-preview'); },
    get styleCellTopColorPreview() { return byId<HTMLElement>('style-cell-top-color-preview'); },
    get styleTabRightColorPreview() { return byId<HTMLElement>('style-tab-right-color-preview'); },
    get styleGridColorPreview() { return byId<HTMLElement>('style-grid-color-preview'); },
    get styleMarkFillColorPreview() { return byId<HTMLElement>('style-mark-fill-color-preview'); },
    get styleMarkStrokeColorPreview() { return byId<HTMLElement>('style-mark-stroke-color-preview'); },
    get styleMarkLineBackgroundColorPreview() { return byId<HTMLElement>('style-mark-line-background-color-preview'); },
    get styleAssistLineColorPreview() { return byId<HTMLElement>('style-assist-line-color-preview'); },
    get styleLineBackgroundColorPreview() { return byId<HTMLElement>('style-line-background-color-preview'); },
    get styleTemplateModeReadBtn() { return byId<HTMLButtonElement>('style-template-mode-read'); },
    get styleTemplateModeEditBtn() { return byId<HTMLButtonElement>('style-template-mode-edit'); },
    get styleTemplateAddBtn() { return byId<HTMLButtonElement>('style-template-add-btn'); },
    get styleTemplateGallery() { return byId<HTMLElement>('style-template-gallery'); },
    get templateColorPopover() { return byId<HTMLElement>('template-color-popover'); },
    get templateColorPopoverTitle() { return byId<HTMLElement>('template-color-popover-title'); },
    get templateColorPopoverPreview() { return byId<HTMLElement>('template-color-popover-preview'); },
    get templateColorPopoverInput() { return byId<HTMLInputElement>('template-color-popover-input'); },
    get templateColorPopoverInputPreview() { return byId<HTMLElement>('template-color-popover-input-preview'); },
    get templateColorPopoverCloseBtn() { return byId<HTMLButtonElement>('template-color-popover-close'); },
    get templateColorPopoverCancelBtn() { return byId<HTMLButtonElement>('template-color-popover-cancel'); },
    get templateColorPopoverSaveBtn() { return byId<HTMLButtonElement>('template-color-popover-save'); }
};
